### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by XDaytan** [chickendrop89/device_xiaomi_sm6225ad-recovery#2]

**Comment by XDaytan** [comment]
Where is the "recovery.img" file?

**Comment by chkndrp** [comment]
In the releases tab on GitHub, here's direct link:

`Recovery Image (IMG)`
https://github.com/chickendrop89/orangefox_device_xiaomi_tapas/releases/latest/download/OrangeFox-Unofficial-tapas.img

`Recovery Archive (ZIP)`
https://github.com/chickendrop89/orangefox_device_xiaomi_tapas/releases/latest/download/OrangeFox-Unofficial-tapas.zip

Flash the recovery via `fastboot` and/or with your existing recovery (with the ZIP)
