### ISSUE TITLE
OTA en ROM settings missing?

### ISSUE THREAD

**Issue by dkoek** [chickendrop89/device_xiaomi_sm6225ad-recovery#3]
I just flashed the latest recovery. I can not find the "enable OTA" setting in the menu like described here: https://wiki.orangefox.tech/en/guides/ota

**Comment by chkndrp** [comment]
The "MIUI OTA" section is removed on devices that support the new virtual A/B partition scheme because it's no longer relevant

**Comment by chkndrp** [comment]
"You cannot set up MIUI OTA in recovery mode for MIUI 13 (MIUI Android 12+) ROMs. These are updated directly by the MIUI updater."

* https://wiki.orangefox.tech/en/guides/ota
